// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;

import 'dart:typed_data' as i2;

import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    boxes,
    animals,
    feedingEvents,
  ];
  late final Shape0 boxes = Shape0(
    source: i0.VersionedTable(
      entityName: 'boxes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 animals = Shape1(
    source: i0.VersionedTable(
      entityName: 'animals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 feedingEvents = Shape2(
    source: i0.VersionedTable(
      entityName: 'feeding_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_20, _column_21, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get qrId =>
      columnsByName['qr_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'qr_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_2(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'created_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);
i1.GeneratedColumn<int> _column_3(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'updated_at',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
  defaultValue: const i1.CustomExpression(
    'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
  ),
);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get boxId =>
      columnsByName['box_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get commonName =>
      columnsByName['common_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get latinName =>
      columnsByName['latin_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get birthDate =>
      columnsByName['birth_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get birthDateAccuracy =>
      columnsByName['birth_date_accuracy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get tempMin =>
      columnsByName['temp_min']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get tempMax =>
      columnsByName['temp_max']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get humidityMin =>
      columnsByName['humidity_min']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get humidityMax =>
      columnsByName['humidity_max']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get picturePath =>
      columnsByName['picture_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archiveReason =>
      columnsByName['archive_reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get archiveNotes =>
      columnsByName['archive_notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'box_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES boxes(id)',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'active\'',
      defaultValue: const i1.CustomExpression('\'active\''),
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'common_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'latin_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sex',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'birth_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'birth_date_accuracy',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'temp_min',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'temp_max',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'humidity_min',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'humidity_max',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'picture_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'archive_reason',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'archive_notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get animalId =>
      columnsByName['animal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fedAt =>
      columnsByName['fed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'animal_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES animals(id)',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    boxes,
    mediaAssets,
    animals,
    feedingEvents,
  ];
  late final Shape0 boxes = Shape0(
    source: i0.VersionedTable(
      entityName: 'boxes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 mediaAssets = Shape3(
    source: i0.VersionedTable(
      entityName: 'media_assets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_22,
        _column_23,
        _column_24,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 animals = Shape4(
    source: i0.VersionedTable(
      entityName: 'animals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_25,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 feedingEvents = Shape2(
    source: i0.VersionedTable(
      entityName: 'feeding_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_20, _column_21, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mimeType =>
      columnsByName['mime_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get data =>
      columnsByName['data']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_24(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'data',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get boxId =>
      columnsByName['box_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get commonName =>
      columnsByName['common_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get latinName =>
      columnsByName['latin_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get birthDate =>
      columnsByName['birth_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get birthDateAccuracy =>
      columnsByName['birth_date_accuracy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get tempMin =>
      columnsByName['temp_min']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get tempMax =>
      columnsByName['temp_max']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get humidityMin =>
      columnsByName['humidity_min']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get humidityMax =>
      columnsByName['humidity_max']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get picturePath =>
      columnsByName['picture_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pictureMediaId =>
      columnsByName['picture_media_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archiveReason =>
      columnsByName['archive_reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get archiveNotes =>
      columnsByName['archive_notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'picture_media_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES media_assets(id)',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    mediaAssets,
    boxes,
    animals,
    feedingEvents,
  ];
  late final Shape3 mediaAssets = Shape3(
    source: i0.VersionedTable(
      entityName: 'media_assets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_22,
        _column_23,
        _column_24,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 boxes = Shape5(
    source: i0.VersionedTable(
      entityName: 'boxes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_26,
        _column_27,
        _column_28,
        _column_25,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 animals = Shape4(
    source: i0.VersionedTable(
      entityName: 'animals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_25,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 feedingEvents = Shape2(
    source: i0.VersionedTable(
      entityName: 'feeding_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_20, _column_21, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get qrId =>
      columnsByName['qr_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get widthCm =>
      columnsByName['width_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get heightCm =>
      columnsByName['height_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get depthCm =>
      columnsByName['depth_cm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get pictureMediaId =>
      columnsByName['picture_media_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'width_cm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'height_cm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_28(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'depth_cm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
