title: TerraManager
description: Lokale und datenschutzfreundliche Terrarienverwaltung
url: "https://codefrogcf.github.io"
baseurl: "/TerraManager"
lang: de
theme: jekyll-theme-minimal

exclude:
  - README.md
